services:
  mysql_db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=notes
      - MYSQL_USER=notes
      - MYSQL_PASSWORD=notes
    networks:
      - notes
  # postgres:
  #   image: postgres:latest
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   ports:
  #     - 5432:5432
  #   shm_size: 128mb
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres # default is already postgres
  #     - POSTGRES_DB=cashflow

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8088:8080
    environment:
      - ADMINER_DESIGN=dracula
      - ADMINER_DEFAULT_SERVER=mysql_db
    depends_on:
      - mysql_db
    networks:
      - notes

networks:
  notes:
    driver: bridge
    name: notes

volumes:
  mysql_data:
    driver: local
